In [4]:
import torch
import numpy as np

In [5]:
arr = [1,2,3]

In [6]:
narr = np.array(arr)

In [9]:
tens =  torch.from_numpy(narr)

In [11]:
torch.as_tensor(arr)

tensor([1, 2, 3])

In [12]:
arr2d = np.arange(0,12) 

In [14]:
arr2d = arr2d.reshape(4,3)

In [15]:
x2 = torch.as_tensor(arr2d)

In [16]:
x2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], dtype=torch.int32)

In [17]:
arr

[1, 2, 3]

In [18]:
narr

array([1, 2, 3])

In [19]:
narr[0]=99

In [20]:
narr

array([99,  2,  3])

In [22]:
tens

tensor([99,  2,  3], dtype=torch.int32)

In [23]:
arr = np.array([0,5,6])

In [24]:
t = torch.tensor(arr)

In [25]:
t

tensor([0, 5, 6], dtype=torch.int32)

In [26]:
t2 = torch.from_numpy(arr)

In [27]:
t2

tensor([0, 5, 6], dtype=torch.int32)

In [28]:
arr[0]=99

In [29]:
t2

tensor([99,  5,  6], dtype=torch.int32)

In [30]:
t

tensor([0, 5, 6], dtype=torch.int32)

In [31]:
new_arr= np.array([1,2,3])

In [32]:
new_arr.dtype

dtype('int32')

In [33]:
import torch
torch.Tensor(new_arr)

tensor([1., 2., 3.])

In [34]:
torch.empty(4,2)

tensor([[ 0.0000e+00,  0.0000e+00],
        [ 2.1019e-44,  0.0000e+00],
        [-3.1440e-09,  4.8065e-43],
        [ 0.0000e+00,  0.0000e+00]])

In [35]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [36]:
torch.ones(4,3,dtype=torch.int64)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [37]:
torch.linspace(0,18,12).reshape(4,3)

tensor([[ 0.0000,  1.6364,  3.2727],
        [ 4.9091,  6.5455,  8.1818],
        [ 9.8182, 11.4545, 13.0909],
        [14.7273, 16.3636, 18.0000]])

In [38]:
torch.tensor([1,2,3])


tensor([1, 2, 3])

In [39]:
mytensor = torch.tensor([1,2,3])

In [40]:
mytensor.dtype

torch.int64

In [41]:
mytensor = mytensor.type(torch.int32)

In [42]:
mytensor.dtype

torch.int32

In [43]:
torch.rand(4,3)

tensor([[0.8245, 0.8734, 0.3598],
        [0.3877, 0.8740, 0.1938],
        [0.9489, 0.5272, 0.6953],
        [0.9575, 0.5231, 0.5958]])

In [44]:
torch.randn(4,4)

tensor([[ 0.5477, -0.1507, -0.1227,  1.3071],
        [-1.0872,  0.0073,  1.5533, -0.4566],
        [ 0.5678,  0.6195,  0.2249,  0.3359],
        [-1.4738,  0.2048,  0.4622,  0.8049]])

In [45]:
torch.randint(low = 0,high = 20,size=(5,5))

tensor([[17,  1,  5,  3,  8],
        [ 7, 12, 11, 13,  1],
        [ 5,  4, 11, 11,  9],
        [17,  8,  4,  3, 17],
        [19, 14, 18, 11,  5]])

In [46]:
x = torch.zeros(2,5)
x.shape

torch.Size([2, 5])

In [47]:
torch.rand_like(x)

tensor([[0.2741, 0.3912, 0.1033, 0.8811, 0.6564],
        [0.5587, 0.9363, 0.2278, 0.7855, 0.6624]])

In [48]:
torch.randn_like(x)

tensor([[ 0.9637, -2.4982, -0.7231, -0.6006,  0.4243],
        [ 1.8373,  1.4585,  0.6777,  0.1300, -1.1308]])

In [49]:
torch.randint_like(x,low=0,high=11)

tensor([[3., 8., 1., 4., 1.],
        [8., 6., 2., 5., 4.]])